name: leak_tracker_minimal_dart_example

environment:
  sdk: '>=2.19.0-317.0.dev <3.0.0'

dependencies:
  leak_tracker: ^1.0.0-dev.1.3

dependency_overrides:
  flutter_lints: ^2.0.0
  leak_tracker:
    path: ..
