include: package:dart_flutter_team_lints/analysis_options.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true

linter:
  rules:
    - avoid_print
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - curly_braces_in_flow_control_structures: false
