include: package:dart_flutter_team_lints/analysis_options.yaml

linter:
  rules:
    - avoid_catching_errors
    - comment_references
    - only_throw_errors
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - unawaited_futures
