name: leak_tracker_minimal_flutter_example

publish_to: 'none'

environment:
  sdk: '>=2.19.0-347.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
