name: leak_tracker_minimal_flutter_example
publish_to: 'none'

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  # The version is `any` because it is defined by flutter_test, whish depends on leak_tracker.
  leak_tracker: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
