name: test_helpers
version: 0.0.1
publish_to: none
description: test helpers

environment:
  sdk: ^3.2.0
  flutter: '>=3.18.0-18.0.pre.54'

dependencies:
  flutter:
    sdk: flutter
  leak_tracker: '>=10.0.8 <11.0.0'
  leak_tracker_testing: '>=3.0.1 <4.0.0'
  matcher: ^0.12.16
  meta: ^1.8.0

dev_dependencies:
  dart_flutter_team_lints: ^3.1.0
  layerlens: ^1.0.16
  test: ^1.25.0
