name: Dart

on:
  schedule:
    # “At 00:00 (UTC) on Sunday.”
    - cron: '0 0 * * 0'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v2
        with:
          channel: stable

      - name: flutter --version
        run: flutter --version

      - name: flutter pub get
        working-directory: .
        run: flutter pub get

      - name: flutter analyze
        run: flutter analyze

      - name: dart test
        run: dart test test/dart

      - name: flutter test
        run: flutter test test/flutter
